### ISSUE TITLE
Chapter 5 : observable-events-http.ts

### ISSUE THREAD

**Issue by mesrine** [Farata/angular2typescript#28]
Not really an error, but confusing for a beginner like me ;)

Line 19:
selector: "app-root",

according to the other examples
selector: "app",

**Comment by yfain** [comment]
I agree, naming selectors could have been more consistent. In Angular CLI-generated project, it's consistent - the default selector is app-root unless you change the prefix property during the project generation or in the file .angular-cli.json.

The code samples in the Angular4 directory where generated with Angular CLI and the naming should be consistent there.
