### ISSUE TITLE
wrong URL in Rest-Request

### ISSUE THREAD

**Issue by mesrine** [Farata/angular2typescript#29]
Hey,

File:
Angular4/http-node-samples/client/src/app/restclientform/product.service.ts
Line 12: (solution)
return this.http.get(`/api/products/${productID}`)

the original URL (without '/api/) doesn't fit the proxy spezification

Greetings

**Comment by yfain** [comment]
Thank, @mesrine! 
I'll fix it here. The thing is that I'm using these code samples for training, and this was the error that I planted on purpose asking students to find the reason of 404 and fix it :)
