### ISSUE TITLE
webpack error in chapter10/auction/client

### ISSUE THREAD

**Issue by mthierba** [Farata/angular2typescript#3]
Hi,
I'm getting this error on `npm start`:
```
ERROR in ./~/bootstrap/dist/css/bootstrap.min.css
Module parse failed: F:\src\angular2typescript\chapter10\auction\client\node_modules\bootstrap\dist\css\bootstrap.min.css Unexpected token (5:83)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (5:83)
    at Parser.pp.raise (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:920:13)
    at Parser.pp.unexpected (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:1483:8)
    at Parser.pp.semicolon (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:1462:73)
    at Parser.pp.parseExpressionStatement (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:1976:8)
    at Parser.pp.parseStatement (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:1754:188)
    at Parser.pp.parseTopLevel (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:1648:21)
    at Parser.parse (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:1616:17)
    at Object.parse (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:882:44)
    at Parser.parse (F:\src\angular2typescript\chapter10\auction\client\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (F:\src\angular2typescript\chapter10\auction\client\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (F:\src\angular2typescript\chapter10\auction\client\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (F:\src\angular2typescript\chapter10\auction\client\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at F:\src\angular2typescript\chapter10\auction\client\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (F:\src\angular2typescript\chapter10\auction\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at F:\src\angular2typescript\chapter10\auction\client\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
 @ ./src/vendor.ts 13:0-47
```

I've already tried various things that people suggested for similar situations, but to no avail so far. Could you kindly check if this needs a fix in the config?

Many thanks,
Mathias

**Comment by antonmoiseev** [comment]
Just tried to run it on my machine, works fine. Let's try two things in order to fix the issue.

## Option 1

Make sure you have a clean fresh copy of the bootstrap library and all the tools involved in processing CSS.

1. Open the `chapter10/auction/client`directory in the command line:

  ```
  $ cd chapter10/auction/client
  ```
2. Run the following git command to remove all the 3rd-party packages and the generated code:

  ```
  $ git clean -fdx
  ```
3. Run `npm install` to install fresh copies of all dependencies.
4. Run `npm start` to launch the app.

## Option 2

You can also try replacing line 15 in the `vendor.ts` file with the following one:

```
import 'bootstrap/dist/css/bootstrap.css';
```

Note, here we import _unminified_ version of the `bootstrap.css` file. In the production build it will be minified anyway.

Please let us know if you still experience this issue.

**Comment by mthierba** [comment]
I've tried both options, but didn't get any further, I'm afraid.

Option 1 (fresh install) gives me the exact same error I have quoted above.

Option 2 (changing to unminified version of bootstrap.css) is incidentally something I had already tried before, and this only gives a slightly different version of the error above. For reference:

```
ERROR in ./~/bootstrap/dist/css/bootstrap.css
Module parse failed: F:\src\angular2typescript\chapter10\auction\client\node_modules\bootstrap\dist\css\bootstrap.css Unexpected token (7:5)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (7:5)
    at Parser.pp.raise (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:920:13)
    at Parser.pp.unexpected (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:1483:8)
    at Parser.pp.semicolon (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:1462:73)
    at Parser.pp.parseExpressionStatement (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:1976:8)
    at Parser.pp.parseStatement (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:1754:188)
    at Parser.pp.parseTopLevel (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:1648:21)
    at Parser.parse (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:1616:17)
    at Object.parse (F:\src\angular2typescript\chapter10\auction\client\node_modules\acorn\dist\acorn.js:882:44)
    at Parser.parse (F:\src\angular2typescript\chapter10\auction\client\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (F:\src\angular2typescript\chapter10\auction\client\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (F:\src\angular2typescript\chapter10\auction\client\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (F:\src\angular2typescript\chapter10\auction\client\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at F:\src\angular2typescript\chapter10\auction\client\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (F:\src\angular2typescript\chapter10\auction\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at F:\src\angular2typescript\chapter10\auction\client\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
 @ ./src/vendor.ts 13:0-43
```

Just to be extra-safe, I also upgraded my local node installation from 5.5 to 6.2, with exactly the same outcomes.

I've run through the same process on an entirely different machine, where I had never checked out the repo before, and got the exact same errors. Hence, this absolutely seems to be reproducible for me.

**Comment by dkataiev** [comment]
Hi. I'm getting the same problem.
I tried both solutions, but nothing helps. :(

**Comment by catull** [comment]
I have two issues.

I have a clean clone of the code checked out.
When I run   `npm run build` the `prebuild` task is run.
Now, this `prebuild` tasks cleans - deletes dist/ -, that's fine, but it immediately runs the test suite.

For the following 3 issues I have suggested solutions for the first 2.

# First issue
Call me old-fashioned, but why would you run a test BEFORE having built anything ?

If I remove the `prebuild` task, I can run the `build` task with various warnings, but at least it builds.

**Fix**: remove the `prebuild` task.

# Second issue
Why are the dev dependencies defined - for `karma`, `rimraf`, `webpack` etc - but in the scripts section they are not prefixed with `node_modules/.bin/karma` etc ?

This means that npm installs the dev dependencies, but you still need them installed globally where they are picked from the $PATH.  You may have an incompatible or outdated version installed in the $PATH, who knows ?

**Fix**: prefix the dev commands with 'node_modules/.bin/karma' etc.

# Third issue
If I run `npm test` or `npm run test`, no test is actually run successfully.

Here's the output:

```log
➜  client git:(master) ✗ npm test

> Chapter_10_Auction@ test angular2typescript.git/chapter10/auction/client
> karma start karma.conf.js


START:
ts-loader: Using typescript@2.0.0 and angular2typescript.git/chapter10/auction/client/tsconfig.json
19 08 2016 23:55:28.952:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
19 08 2016 23:55:28.972:INFO [launcher]: Starting browser Chrome
19 08 2016 23:55:28.993:INFO [launcher]: Starting browser Firefox
19 08 2016 23:55:33.289:INFO [Chrome 52.0.2743 (Mac OS X 10.11.6)]: Connected on socket /#RPd5tUvAjsLznfl4AAAA with id 42207960
Chrome 52.0.2743 (Mac OS X 10.11.6) ERROR
  Uncaught Error: Missing: SyncTestZoneSpec
  at angular2typescript.git/chapter10/auction/client/karma-test-runner.js:2821
19 08 2016 23:55:36.644:INFO [Firefox 48.0.0 (Mac OS X 10.11.0)]: Connected on socket /#mW4SVXPzg2HfBeOGAAAB with id 39354343
Firefox 48.0.0 (Mac OS X 10.11.0) ERROR
  Error: Missing: SyncTestZoneSpec
  at angular2typescript.git/chapter10/auction/client/karma-test-runner.js:2821

Finished in 0.789 secs / 0 secs

SUMMARY:
✔ 0 tests completed
```

**Fix**: No clue how to solve this.

**Comment by dkataiev** [comment]
@antonmoiseev and @catull can you please provide you versions of node and npm ?

**Comment by catull** [comment]
Certainly.

Node is 6.4.0, npm is 3.10.6.
Which ones are yours ?

Thanks.

**Comment by dkataiev** [comment]
Just updated to the same versions.
node: v6.4.0
npm: 3.10.3

**Comment by catull** [comment]
I am aware I am not addressing the original posters problem.
The problem occurred in May, with nodejs 6.2.
It is not known if @mthierba still persists.

**Comment by catull** [comment]
If I leave the `prebuild` task in, but with the other two suggested fixes, I can run all tasks.

**Comment by catull** [comment]
Can you please address the three "issues", whether they are "issues" in your opinion ?

**Comment by dkataiev** [comment]
The atrange thing is that i created a [starter project](https://github.com/dkataiev/angular-bootstrap-webpack-starter) based on client code. If i run npm run build directly in this starter - everything is ok.
After that i copy files to another folder (only source code, without node_modules), and then i get subj error.

**Comment by dkataiev** [comment]
@catull I'm very new to Angular2 and it is hard for me to say if your two first issues are really issues.

I also faced problem with zone.js and fixed it in the same way as you did.

**Comment by catull** [comment]
I am also rather new to angular 2, we're in the same boat on the same ocean.

**Comment by dkataiev** [comment]
And this ocean is full of sharks and mysterious creatures ;)

**Comment by catull** [comment]
I checked out your repo, and I can only run `npm run build` successfully, if zone.js is exacly 0.6.12.
Now which files do you copy ?

Are there the ones?

karma*.js
package.json
src/   -- the whole folder
tsconfig.json
webpack*

?

**Comment by catull** [comment]
Can you give me the first 10 lines of that bootstrap.css, the one that is reported as having an unexpected token ....

**Comment by dkataiev** [comment]
```css
/*!
 * Bootstrap v3.3.7 (http://getbootstrap.com)
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */
/*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
html {
  font-family: sans-serif;
  -webkit-text-size-adjust: 100%;
      -ms-text-size-adjust: 100%;
}
```

this are the first 10 lines

**Comment by catull** [comment]
Yepp, I have the exact same lines, I was hoping there was a typo ...

**Comment by dkataiev** [comment]
So for everything is ok ?

**Comment by catull** [comment]
I think there is a mistake in vendor.ts.

Why don't you comment this line in 

```ts
import 'bootstrap/dist/css/bootstrap.min.css';
```

The error to me says, the compiler expects a TypeScript package/class, but the referenced file is a CSS file.

Just to see if the build works, comment line 15 in vendor.ts.

**Comment by catull** [comment]
Installation:  I downloaded node 6.4.pkg (form Mac OS X).
Ran the installer and it installed it in /usr/local, as always.
It installs node and npm.  I have installed node js 4.x.y, 5.x.y, and 6.x.y, various sub-versions.
I only keep one version at a time.

**Comment by dkataiev** [comment]
Lokks like i broke my node and npm installation. I'll try to reinstall it again, maybe this will help.

**Comment by catull** [comment]
Which OS and version do you use ?

**Comment by dkataiev** [comment]
OSX 10.11.6

**Comment by catull** [comment]
Do you install npm packages globally ?

**Comment by dkataiev** [comment]
Not sure.
How do you install webpack or karma ?

**Comment by catull** [comment]
You can install it two ways.  For your user only, or globally.

User-only:  npm install karma  -- the packages are installed in $HOME/.npm I think.
Globally:     npm install -g karma -- per default, the packages are installed in /usr/local/lib/node_modules.

Inside a node project, you do this:    npm init  (it creates a simple package.json)
Then you install packages like in the User-only case.
Only now they are installed in node_modules in the same directory.
But you can also instruct npm to save the version in package.json

npm install karma --save-dev    -- the package is defined in "devDependencies" section
npm install bootstrap --save     -- the package is defined in  "dependencies" section

**Comment by catull** [comment]
Typically, I install a few npm packages globally, such as grunt, gulp, TypeScript.
Since they are installed in /usr/local/bin, I can use then in the shell.

But for development, you typically create a package.json and install the dependent packages locally, in the same folder where package.json is stored, under node_modules.

**Comment by catull** [comment]
So, how are you coming along?
Got node re-installed ?
Is it working or the error is back ?

**Comment by catull** [comment]
In your shell, can you type these two lines ?

which webpack

webpack --version

What are the results ?

**Comment by dkataiev** [comment]
I don't understand how but i made it work without errors.

**Comment by catull** [comment]
Great!
