### ISSUE TITLE
Unable to launch Ch 2 solution

### ISSUE THREAD

**Issue by aaonline** [Farata/angular2typescript#31]
Using Google Chrome I get following error

Failed to load file://Web/AngularWithTypescript/Chp1/main.ts: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

Please suggest.

**Comment by yfain** [comment]
Which app from CH2 gives you this error?  How do you run this app? Which versions of node.js and Angular CLI do you have installed?

**Comment by aaonline** [comment]
This code https://github.com/Farata/angular2typescript/tree/master/chapter2/hello-world-ts gave error.

I did not use node.js, etc as this is first angular example. So I just wrote the html and ts file and launched them in Google Chrome. I hope I am doing right here.

**Comment by aaonline** [comment]
This is fixed,

I started running http-server -o pointing it to the chapter2/hello-world-ts  source code directory locally and it worked. So perhaps, this does not work without Node.js.

**Comment by yfain** [comment]
This has nothing to do with node.js. You should run this example using any web server. For example, you can go into the hello-world-ts directory and just run http-server from there.
