### ISSUE TITLE
chapter 2 auction  can not display

### ISSUE THREAD

**Issue by Suhesong** [Farata/angular2typescript#35]
![image](https://user-images.githubusercontent.com/23503290/44086990-f0b8f1bc-9ff0-11e8-9f89-341144f32d1d.png)
![image](https://user-images.githubusercontent.com/23503290/44087030-0ca4d44a-9ff1-11e8-8584-2c161e1b131c.png)
how should i do？

**Comment by Fibird** [comment]
Suggest using typescript 3, you can change ts's version package.json

**Comment by yfain** [comment]
This book is old. We don't use SystemJS any longer. Please use the code samples from the second edition of the book https://github.com/farata/angulartypescript.
