### ISSUE TITLE
Chapter 2 - Hello World TS - doesn't work

### ISSUE THREAD

**Issue by vorant94** [Farata/angular2typescript#36]
I've tried to run this example from the book, and it failed. After that, I found your repository (thank you a lot by the way) and tried to run this time your code but got the same issue. I can go and read the rest of the book, but if it is possible I want also to run the simplest "hello world"... but I can't

Here is the screenshot of error when running it in browser
![screenshot](https://imgbbb.com/images/2020/01/30/Screen-Shot-2020-01-30-at-09.07.33.png)

**Comment by yfain** [comment]
Please try to find a similar code sample in the repository for the newer edition of this book at https://github.com/Farata/angulartypescript

**Comment by vorant94** [comment]
@yfain I can't find there examples of hello world's

**Comment by yfain** [comment]
We don't use SystemJS for loading modules anymore. That's why that version of  HelloWorld was not included in the second edition.  Simply compile the TypeScript code to JavaScript and include the compiled version in the file index.html.
